cloud:
  aws:
    credentials:
      access-key: 
      secret-key: 
    region:
      static: 
    stack:
      auto: false

application:
  bucket:
      name: 


spring: <1 key>

server:
  port: 8083

